[theme]
base="light"
primaryColor="#2b6777"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#1f1f1f"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=false

[python]
extraPaths = ["src"]