[theme]
primaryColor = "#2ECC71"
backgroundColor = "#F8F9F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2C3E50"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = true

[general]
pageTitle = "CruscottoPMI"